### ISSUE TITLE
搜索框键盘事件应增长延时

### ISSUE THREAD

**Issue by JexCheng** [staticfile/staticfile.github.com#14]
现在感觉是每输入一个字符就发起请求搜索一次，页面很卡。

**Comment by Xuanwo** [comment]
目前的延时是200ms，你觉得还需要加长么？

**Comment by JexCheng** [comment]
https://github.com/staticfile/staticfile.github.com/blob/master/static/app.js#L38

这里shift仅仅clearTimeout取消队列中等待的动作，但发出去的请求动作及相应的回调动作并没有取消，所以我用略大于200ms的敲键速度输入「jquery」只花了一秒，但会总共发出6个请求，并且对视图进行6次更新，你没觉得卡吗？

**Comment by Xuanwo** [comment]
有道理，我会花一点时间将搜索这块重做一下。关于模糊搜索，有什么好的实现么？我对这块不是非常了解~

**Comment by JexCheng** [comment]
我不知道现在Lib总数有多少，估计将name和description全部一次性加载到客户端也是可行的，或者按提交日期拆分成几个文件利于缓存。
然后客户端JS运行个[Levenshtein算法](https://en.wikipedia.org/wiki/Levenshtein_distance)应该就足够了，当用户拼错成 jqeury时也能给出一些结果。

**Comment by Xuanwo** [comment]
好的，感谢您的建议，我研究研究~

**Comment by Xuanwo** [comment]
Closed for using new algorithm.
